// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzryPsG34Z4hN4oRBQM9vtOKSKqoNc4fc',
    appId: '1:780736640622:web:7d5f032f5f4af956fd587f',
    messagingSenderId: '780736640622',
    projectId: 'fauzi-portofolio-978ae',
    authDomain: 'fauzi-portofolio-978ae.firebaseapp.com',
    storageBucket: 'fauzi-portofolio-978ae.appspot.com',
    measurementId: 'G-57JVBWG9FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKfQ2Ceuddu0DaFO9Ng1qBjYuWOrSWcJ0',
    appId: '1:780736640622:android:13144ba2b146e4e8fd587f',
    messagingSenderId: '780736640622',
    projectId: 'fauzi-portofolio-978ae',
    storageBucket: 'fauzi-portofolio-978ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvQmSqGNrdJLawFIvsESGWINhtwWc2fRk',
    appId: '1:780736640622:ios:31a7be5c27c37159fd587f',
    messagingSenderId: '780736640622',
    projectId: 'fauzi-portofolio-978ae',
    storageBucket: 'fauzi-portofolio-978ae.appspot.com',
    iosBundleId: 'com.fauziarifarnami.fauziPortofolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvQmSqGNrdJLawFIvsESGWINhtwWc2fRk',
    appId: '1:780736640622:ios:31a7be5c27c37159fd587f',
    messagingSenderId: '780736640622',
    projectId: 'fauzi-portofolio-978ae',
    storageBucket: 'fauzi-portofolio-978ae.appspot.com',
    iosBundleId: 'com.fauziarifarnami.fauziPortofolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzryPsG34Z4hN4oRBQM9vtOKSKqoNc4fc',
    appId: '1:780736640622:web:9aef546278a9e228fd587f',
    messagingSenderId: '780736640622',
    projectId: 'fauzi-portofolio-978ae',
    authDomain: 'fauzi-portofolio-978ae.firebaseapp.com',
    storageBucket: 'fauzi-portofolio-978ae.appspot.com',
    measurementId: 'G-ME4PQ4SQ57',
  );
}
